language: go
go:
  - 1.14.2

before_install:
  - go get -t -v ./...

script:
  - go test -v -coverprofile=coverage.coverprofile -covermode=atomic
  
after_success:
  - bash <(curl -s https://codecov.io/bash)